### ISSUE TITLE
cdnizer Bundling Scripts incorrectly?

### ISSUE THREAD

**Issue by computersarecool** [OverZealous/cdnizer#27]
Hi,

In my `.bower.json` I have the following:

```json
 "dependencies": {
  "angular": "1.5",
  "angular-resource": "1.5",
  "angular-sanitize": "1.5",
  "angular-route": "1.5"
}
```

In my `index.html` I have
```html
  <script src="../bower_components/angular/angular.js"></script>
  <script src="../bower_components/angular-resource/angular-resource.js"></script>
  <script src="../bower_components/angular-sanitize/angular-sanitize.js"></script>
  <script src="../bower_components/angular-route/angular-route.js"></script>
```

But after running cdnizer, I am left with the following:
```html
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular/angular.js");</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular-resource/angular-resource.js");</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular-sanitize/angular-sanitize.js");</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular-route.min.js"></script><script>if(!(window.angular)) cdnizerLoad("../bower_components/angular-route/angular-route.js");</script>
```

In looking at the [documentation](https://docs.angularjs.org/api/ngResource) it does not look like the `resource`, and `sanitize` packages are bundled, but here they are replaced with, and only checked with the larger angular.min script.

Furthermore, if they *were* bundled, having those three fallbacks seem redundant.

Is there a way that I can confirm if these packages should be bundled, and if they are not include the three `script` tags.  Or, is this ideal for some reason?

**Comment by OverZealous** [comment]
[It's a known bug.](https://github.com/OverZealous/cdnizer/issues/16#issuecomment-121323809)

Just add `allowRev: false` to your cdnizer config.

The `allowRev` is designed to work with hash-based revisioning, and it aggressively matches `-.{8}` at the end of the file name, which causes problems with anything that has that format.

I know it's been out there for a long while, I really should change the default options.

**Comment by computersarecool** [comment]
That does it thanks!
